FROM node:latest

WORKDIR /usr/workdir/api

COPY . .
COPY ./.env.production ./.env

RUN npm install --quiet --no-oprional --no-fund --loglevel=error

RUN npm run build

EXPOSE 3000

CMD ["npm", "start", "start:prod"]
